### ISSUE TITLE
Add "Patches" view for applying Gameshark patches

### ISSUE THREAD

**Issue by PartyPlanner64** [PartyPlanner64/PartyPlanner64#10]
When a ROM is loaded, it would nice to have way to easily patch the ROM with various patches. Off the top of my head, these are some that might be useful:
- Patch to unlock all the boards for a particular game without having to earn all stars
- Patch to unlock Daisy/Waluigi
- Patch for that tank Mini-Game in MP2 to have 4 lives

Any other thoughts?

**Comment by XModxGodX** [comment]
How about a patch to play/edit the "how to play" boards like Rules Land in MP2?

**Comment by PartyPlanner64** [comment]
The Rules boards don't have the full set of assets or event code. What someone can do eventually would be just recreate the rules board as a normal board, and design the rest of the image assets it would need.

**Comment by PartyPlanner64** [comment]
Committed a basic patches view in 21d1924, so closing this issue. Didn't specifically do any of these patches yet.
