### ISSUE TITLE
Ability to show an additional background permanently in the editor

### ISSUE THREAD

**Issue by Airsola01** [PartyPlanner64/PartyPlanner64#109]
For the Additional Backgrounds feature, could we have it so that clicking an additional background keeps it on-screen until you either click it again (to undo) or click another additional background? (in other words, not have PartyPlanner go back immediately to the main background when you release the mouse click)

ty c:

**Comment by PartyPlanner64** [comment]
There is now an "eye" button for each additional background (similar to the photoshop layer visibility icon). Clicking this button toggles the visibility of the button, so it is no longer based on mouse press.

Fixed in 1ac64460792fa6e451829d77f8cd0bd329f91796.
