### ISSUE TITLE
Have an accessible "space count" to track number of spaces (and what type) added.

### ISSUE THREAD

**Issue by Lego6245** [PartyPlanner64/PartyPlanner64#110]
When analyzing created boards, it's helpful to know how many of each space type are present to allow for better planning (i.e. most  Mario Party boards have ~90-100 spaces, half are blues, etc.)

The following snippet run in console counts total spaces, but I was envisioning either a part of the UI or a menu option providing this count:

`window._PP64instance.state.currentBoard.spaces.reduce((a, c) => a + (c.type !== 0 && c.type !== 7 && c.type !== 5 && c.type !== 13 ? 1 : 0), 0)`

**Comment by PartyPlanner64** [comment]
I think it's a good idea, and a "stats" screen for boards would be a reasonable way to implement this.

**Comment by PartyPlanner64** [comment]
Fixed in 774562b67. The board details page now contains counts of each space type, and totals of all spaces and solid spaces (spaces characters can land on).
