### ISSUE TITLE
Custom Music that replaces in-game MIDIs does not loop

### ISSUE THREAD

**Issue by Airsola01** [PartyPlanner64/PartyPlanner64#111]
When you add your own MIDIs using the Audio feature, the songs do not loop, which just leads to the game playing no music after the track is done. The best solution I can see to this would be having a true/false checkbox next to the play button so that the creator can just mark down whether they want this song to loop or not. Otherwise, it would be nice if it would just loop everything.

**Comment by PartyPlanner64** [comment]
I've changed the Audio page to loop any midi that is replaced by default (566d9bb5f3dabf062498136839927beb9ad2392f). If there is a use case to not loop, there could be some UI added to control it.

Support for multiple MIDIs attached to a board was also added, which most likely supersedes most usage of the Audio page now.
