### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by PIUPhones** [PartyPlanner64/PartyPlanner64#114]
**Describe the bug**
The desktop program won't load and will only show a plain brown screen, this happened after I mistakenly clicked on a file that was not compatible with the program, and re-downloading it did not help

**To Reproduce**
1. Open PartyPlanner64
2. Click on Import File
3. Scroll down to Any non .json .c or .s file

**Web browser or Desktop version?**
Desktop
![unknown (1)](https://user-images.githubusercontent.com/78895496/107606084-f170e280-6c2c-11eb-9a21-cfb50ebae552.png)

**Comment by PartyPlanner64** [comment]
Please try the [newest release](https://github.com/PartyPlanner64/PartyPlanner64/releases) - I think issues with the Windows version should be fixed.
