### ISSUE TITLE
Crash issue when a bank space is placed in Mario Party 3 style

### ISSUE THREAD

**Issue by JuliaPseudo** [PartyPlanner64/PartyPlanner64#120]
I got this error after placing a bank space in the Mario Party 3 game style. Other spaces work fine. Tested on Firefox and Chrome, both latest versions.

The error can be evaded by placing another type of space, then changing it to a bank space and adding a bank event.

Error: Minified Redux error #3; visit https://redux.js.org/Errors?code=3 for the full message or use the non-minified dev environment for full errors. 

Stack Error Details:

c@https://partyplanner64.github.io/PartyPlanner64/static/js/2.c570e567.chunk.js:2:946950
Ur@https://partyplanner64.github.io/PartyPlanner64/static/js/main.313818f2.chunk.js:2:436420
value@https://partyplanner64.github.io/PartyPlanner64/static/js/main.313818f2.chunk.js:2:1013765
Ks@https://partyplanner64.github.io/PartyPlanner64/static/js/main.313818f2.chunk.js:2:1070416
addSpaceAction@https://partyplanner64.github.io/PartyPlanner64/static/js/main.313818f2.chunk.js:2:423980
Ne/g</</</<@https://partyplanner64.github.io/PartyPlanner64/static/js/2.c570e567.chunk.js:2:953857
e/this.produce@https://partyplanner64.github.io/PartyPlanner64/static/js/2.c570e567.chunk.js:2:943744
Ne/g</</<@https://partyplanner64.github.io/PartyPlanner64/static/js/2.c570e567.chunk.js:2:953832
Ne/g</<@https://partyplanner64.github.io/PartyPlanner64/static/js/2.c570e567.chunk.js:2:953734
t.default/<@https://partyplanner64.github.io/PartyPlanner64/static/js/2.c570e567.chunk.js:2:1738902
me/<@https://partyplanner64.github.io/PartyPlanner64/static/js/2.c570e567.chunk.js:2:948298
h@https://partyplanner64.github.io/PartyPlanner64/static/js/2.c570e567.chunk.js:2:947332
jr/</<@https://partyplanner64.github.io/PartyPlanner64/static/js/main.313818f2.chunk.js:2:435626
ye/</</<@https://partyplanner64.github.io/PartyPlanner64/static/js/2.c570e567.chunk.js:2:949179
Js@https://partyplanner64.github.io/PartyPlanner64/static/js/main.313818f2.chunk.js:2:1070265
mu@https://partyplanner64.github.io/PartyPlanner64/static/js/main.313818f2.chunk.js:2:1238923
Zc@https://partyplanner64.github.io/PartyPlanner64/static/js/main.313818f2.chunk.js:2:1231635
Kc@https://partyplanner64.github.io/PartyPlanner64/static/js/main.313818f2.chunk.js:2:1229712

Component Stack Error Details:

N/A

**Comment by PartyPlanner64** [comment]
Was a recent regression, should be fixed now. Thanks!
