### ISSUE TITLE
Custom Headers 

### ISSUE THREAD

**Issue by Mimic-exe** [PartyPlanner64/PartyPlanner64#128]
Currently when a user makes a custom map the Header is missing as found in the official boards. 
![image](https://user-images.githubusercontent.com/102052961/159328854-143c2b03-4466-43e2-9976-d3295315bfe7.png)
And when players finishes a custom map the map that was over written displays it's header. 
![image](https://user-images.githubusercontent.com/102052961/159329291-76292298-e845-4ed3-b978-6701cf57a0e7.png)
I would be nice to be able to have custom boards that display their unique header on the pause menu and the result screen.

**Comment by PartyPlanner64** [comment]
Any place that is showing the original board graphics is definitely an oversight.

My approach was to try to blank these out, just to try to keep the amount of graphics needed for a custom board to a minimum. But it would be a fine change to support custom graphics for these; I could just make the default a transparent image, and if a board creator doesn't want to bother, that would be just as good as the behavior today.

**Comment by PartyPlanner64** [comment]
The stock logo that showed up on the board "stats" screen is now made transparent by default (835e8d263a29d1ef41071fbc35be67a74f35afdf) and custom boards can now customize both of these logos (20ce986f9eaf7419773865ba95eb12e8a7dc1388).

These logos are called the "small" and "medium" logos, and are set from the details page.
