### ISSUE TITLE
Saving in MP3 does not work

### ISSUE THREAD

**Issue by PartyPlanner64** [PartyPlanner64/PartyPlanner64#18]
User reported:
After turning of the game and the opening it again, save file doesn't work.

Need to confirm if this works on real hardware. If so, probably a bad emulator assumption.

**Comment by SuperZambezi** [comment]
Wanted to add on to this. If you press Start in the middle of a turn, quit, and then return, your turn will start at the exact spot you left off at. So if you turned it off after moving halfway through your roll or at an intersection, that's where your turn will start when you come back. You could actually use this to never let your turn end.

Test in MP1 and MP2, those games save fine.

**Comment by P3rf3ctXZer0** [comment]
MP3 does not save at all; also using my map I keep crashing on the 3rd turn. 
[Boards-Valentine Islands-v7.zip](https://github.com/PartyPlanner64/PartyPlanner64/files/676402/Boards-Valentine.Islands-v7.zip)

**Comment by PartyPlanner64** [comment]
gamemasterplc brought to my attention that Mario Party 3 needs to be configured to use the 16K EEPROM save type. If this is done, the game should save correctly in emulators.

In general, I have also written a dedicated page for [emulator setup](https://github.com/PartyPlanner64/PartyPlanner64/wiki/Emulator-Setup).

PartyPlanner64 patches the game so it doesn't _have_ to be ran with 16K EEPROM, but saving won't work if it doesn't.

Closing this issue since I think the save type correction explains these issues.

**Comment by P3rf3ctXZer0** [comment]
I will try to set that. I will post again if it crashes.
