### ISSUE TITLE
Spaces do not line up exactly how they are placed in the editor

### ISSUE THREAD

**Issue by PartyPlanner64** [PartyPlanner64/PartyPlanner64#20]
PP64 is doing a crude conversion from the XY plane to the XYZ coordinates the game uses. It is somewhat accurate at the center of the board but things get off further out.

I had looked into what the game was doing at one point but I never figured out the exact formula. It appears the coordinates go through at least one conversion before probably getting pulled into some display list.

As a temporary workaround, you can compensate by shifting the spaces against whatever direction they are trending.

**Comment by StalfosKing** [comment]
I've created a test to visualize the distortion in-game. I basically made a grid out of spaces and then used a grid as the background so that we can see the skewing of spaces in-game.

[Space Distortion Test.zip](https://github.com/PartyPlanner64/PartyPlanner64/files/576335/Space.Distortion.Test.zip)

**Comment by StalfosKing** [comment]
I've created a test board to visualize and hopefully help calculate the distortion of the positions of the spaces once in-game. It's a map filled with evenly spaced spaces that create a grid on top of a gridded background. This way we can see how the spaces' positioning changes in different parts of the map.
[Space Distortion Test.zip](https://github.com/PartyPlanner64/PartyPlanner64/files/576719/Space.Distortion.Test.zip)

**Comment by PartyPlanner64** [comment]
Thanks, I've done stuff in the past like that to work on the alignment.

Anyone could help with this if they have the ambition. Basically what I had done was just manually created a transformation function from the x,y,z in the ROM to the editor x,y coordinates. For example:

https://github.com/PartyPlanner64/PartyPlanner64/blob/master/js/adapter/MP1.js#L197

What I came up with is kind of non-sensical and it isn't perfect. We either need to come up with a more robust "guesswork" transformation like I have now, or actually figure out how it truly transforms the coordinates.

(The reason we need a transformation at all is clear if you look at how the other board space layouts load. The game stores the spaces as if they are totally on a flat plane, and then at runtime it transforms them in 3D space. The editor needs to be able to transform back to this "flat" style in such a way that it lines up when the game reads the data.)

**Comment by StalfosKing** [comment]
I would be glad to take on this massive task if not for the fact that I know next to nothing about programming. I do have another concern to do with this topic. I've noticed that after patching a ROM and then loading this new ROM back into Party Planner, the spaces in the top half of the screen seem to have been pushed down slightly. What is it that causes this space translation before being rendered in the game? I just want to make sure this is not a bug.

**Comment by PartyPlanner64** [comment]
It's due to the transformation done by PP64 not being an exact inverse. A good fix to the overall issue here would end up addressing that as well.

**Comment by StalfosKing** [comment]
I just had another thought: Nintendo probably made the pre-runtime space layout on top of the 3D board at a flat top-down angle and then tilted the 3D board before pre-rendering it as the background, meaning that we could potentially do the same when making our boards if we found a close enough tilt.

**Comment by Tiquono** [comment]
I've started working on this one myself... I hope to be of service.

**Comment by PartyPlanner64** [comment]
Thanks to some reverse engineering by gamemasterplc, the camera math was figured out (f47d8654d) and this issue is now fixed in the latest release!

This does mean that all current boards which have workaround alignments will now actually show up that way, but the fix to this issue is spot on, so this compatibility break is worth it I think.

**Comment by SpeedyYoshi64** [comment]
Wow. it took 3 years to get it fixed.
