### ISSUE TITLE
Support Undo/Redo

### ISSUE THREAD

**Issue by PartyPlanner64** [PartyPlanner64/PartyPlanner64#22]
Portions of the editor could support undo/redo, particularly interactions like placing spaces or paths.

It would be interesting to try something like Redux for state management to add a feature like this.

**Comment by StalfosKing** [comment]
In my opinion this should be high-priority... Not having an undo function is very damaging to workflow.

**Comment by PartyPlanner64** [comment]
Latest web version includes Undo/Redo support for actions taken in the board editor view. This is invoked via Ctrl+Z/Y.

Closing this issue since the basic feature is now complete. Separate issues could be opened if there are issues with the functionality or it ought to be extended in some way.
