### ISSUE TITLE
Can't Open Rom With Overwritten Board

### ISSUE THREAD

**Issue by SlimKirby64** [PartyPlanner64/PartyPlanner64#25]
Hey PartyPlanner64. I spent last evening creating a board that I was really excited about to share with my friends, but when I was done, I was running into issues with actually playing it. The newly created ROM didn't seem to play with any version of Project 64 I owned. The program did allow me to overwrite DK's Jungle Adventure with my board, to the point where it wouldn't give me any warnings or errors. And if I imported the board back into PP64, it would import properly and show that the overwrite was successful and everything.

Clearly there is probably something "iffy" about the board in question, whether it's too big (or the wrong size in general) or the fact that there might be too much going on, but because I don't know the reason,  I'm at a huge loss on what to do next to try and get this to work, so I came here for some ideas.

Also, I've been trying to attach my board file to this post, but it's not letting me because json is not an appropriate file type. I also tried putting in a zip file to also no avail (even though it says ZIP files are acceptable....)

**Comment by PartyPlanner64** [comment]
Closing this issue, sounds like the solution was to make the emulator use the full 8MB of RAM, which is necessary.
