### ISSUE TITLE
Can't get past splash screen.

### ISSUE THREAD

**Issue by Excodon64** [PartyPlanner64/PartyPlanner64#26]
Hey, I just made a new board for my group of friends on netplay, and when we tried to play the rom, it did the splashes on the splash screen fine, but after that it just went black. If you need I can post the board.

**Comment by PartyPlanner64** [comment]
A crash after the splash screen narrows it down but I still don't really know what it would be. If Github doesn't take the json file can you try a couple other things?

- Try renaming to a .txt file and uploading here.
- Upload to something like mediafire

**Comment by Excodon64** [comment]
[SqurpPls.txt](https://github.com/PartyPlanner64/PartyPlanner64/files/573540/SqurpPls.txt)
I renamed it to a txt, keep in mind it's kind of a joke board, so I didn't intend for the image to be serious.

**Comment by PartyPlanner64** [comment]
There is a validation error about too many banks, so did you enable Skip Overwrite Validation by any chance? Too many banks would cause a crash at least at runtime during the game.

(Also not related to the crash, the characters should be on invisible spaces adjacent to their event spaces, not directly on the player path.)

**Comment by Excodon64** [comment]
Oh sorry, that was the outdated one, I fixed the bank issue. 
[SqurpPlsNew.txt](https://github.com/PartyPlanner64/PartyPlanner64/files/574025/SqurpPlsNew.txt)

**Comment by PartyPlanner64** [comment]
I wrote this newer board file to ROM and it seems to be working fine for me. So I suppose the next questions are:
- What is the emulator?
- Is the emulator set up to run with 8MB RAM? (It should be if you get to the splash screen.)
- What browser are you running PP64 in, and are there any errors in the browser F12 console?

**Comment by Excodon64** [comment]
-Project 64 1.6
-Yes
-Google Chrome, No.

**Comment by Flame8765** [comment]
@Excodon64 I experienced the same issue when using Project 64 1.6 even after running the ROM with 8MB RAM. Switching to PJ64 2.3 worked well which leads me to believe that it isn't the tool's fault.

**Comment by Excodon64** [comment]
Switching to Project 64 2.3 fixed this. Thanks to both @PartyPlanner64 and @Flame8765 for your help!
