### ISSUE TITLE
Star spaces turning into chance time spaces after star is purchased

### ISSUE THREAD

**Issue by StalfosKing** [PartyPlanner64/PartyPlanner64#29]
I've finished my map and when I tested it, I found that once I buy a star and the next star in the rotation is up, the space that the first star was on was then a chance time space, when in the editor I had it as a plain blue space. This happened after I bought each star for some unknown reason.

**Comment by PartyPlanner64** [comment]
This is the behavior of the original boards, so I haven't altered it. It would be possible to remove probably but it would be a very low priority enhancement.
