### ISSUE TITLE
MP3: Poison Mushroom Broken

### ISSUE THREAD

**Issue by SuperZambezi** [PartyPlanner64/PartyPlanner64#31]
Using a Poison Mushroom on someone else doesn't work. The item appears to float around their head, but it does not change the dice block.

If you attempt to use another one (or maybe this is if you use it on yourself), the dice block does change, but the path breaks and you end up back at start before eventually crashing the game, just like the Reverse Mushroom. #21

**Comment by PartyPlanner64** [comment]
I'm not seeing crash or path issues directly related to this, but I am seeing that the item doesn't take effect on the non-active player. I'm thinking there is some event from the stock board that I wipe out that helps control this behavior, and I just need to find it and not erase it anymore.

**Comment by PartyPlanner64** [comment]
I believe this is fixed, commit fd463be. Seems straightforward, but need to be on the watch for any new issues. I think I remember someone saying that the reverse curse also had an issue; if so this probably also fixed it.
