### ISSUE TITLE
Guide arrows not appearing for Mario Party 3 CPUS

### ISSUE THREAD

**Issue by meagpig9001** [PartyPlanner64/PartyPlanner64#33]
When the CPU reaches the first guide arrow, the game soft locks itself. I tested it with a human and the guide arrow worked fine.

**Comment by PartyPlanner64** [comment]
The CPUs haven't been crashing for me at branches, but it is certainly possible that it could be. I would be interested in seeing a board file that exhibits the issue, and I'd like to know to if there is a particular emulator where this happens.

**Comment by meagpig9001** [comment]
https://drive.google.com/file/d/0B8mGOAr_ozIvWUxqSTVmck8tRjQ/view?usp=sharing The game doesn't actually crash. What happens is that the arrows don't appear for the CPUS; so they just stand at the junction. This was in Project 64 2.3.

**Comment by PartyPlanner64** [comment]
I need to investigate Project 64 more.

Unfortunately Project 64 doesn't work very well on Linux, and I can't even use the UI to change the settings to get it to work at all. Would you be able to find the Project64.cfg configuration file that has been modified to make the game run with 8MB? If I could get a copy of that, or just have the relevant parts posted, I could probably get it to boot the modified games.

**Comment by PartyPlanner64** [comment]
Fixed this in the most recent set of commits. Now I give the path split events one of the old AI pointers instead of a null pointer. So the AI still make dumb decisions but it shouldn't hang anymore.

**Comment by meagpig9001** [comment]
Thx! My board works now!

**Comment by SpeedyYoshi64** [comment]
/  -----      -----\
|  o            <      |
\      v              /
