### ISSUE TITLE
MP2: White screen when starting Hexagon Heat Mini-Game

### ISSUE THREAD

**Issue by Flame8765** [PartyPlanner64/PartyPlanner64#36]
Was play-testing a board in Mario Party 2 when the game soft-locked while loading Hexagon Heat, similar to the Tipsy Tourney crash as previously reported. I was using an emulator with the correct settings so I can only guess that it's an issue within the patched ROM.

**Comment by PartyPlanner64** [comment]
I tried this tonight and wasn't able to reproduce the crash in two emulators (nemu, mupen64plus) or on real hardware. I used the game's debug menu to launch the mini-game, which I suppose could be relevant but I wouldn't think so.

My thoughts are that it is either a bug with the specific emulator (Project64?) or maybe something that writing only certain boards would cause.

If you have a board file where this definitely happens, I would like to test with that board.

If you want to get to the Mini-Game through the debug menu:
- Check the Advanced features checkbox in the settings
- Load the ROM, and go to the Patches view from the header of the editor. It might be one of the last items in the dropdown.
- Apply the Debug Menu patch.
- Overwrite a board or save the ROM as usual.

Hexagon Heat is listed something like "IroIro Dash."

**Comment by Flame8765** [comment]
Okay. I just loaded Hexagon Heat via the debug menu and it ran fine. This is the (joke) board I was testing with when the crash occurred: 
[Trump the Game (MP2).json.txt](https://github.com/PartyPlanner64/PartyPlanner64/files/632997/Trump.the.Game.MP2.json.txt)

I may have to do some further testing to see if I can reproduce the crash consistently. I'm unsure how to load the mini-game purposely other than somehow manipulating RNG.

**Comment by PartyPlanner64** [comment]
I looked into this and I believe it is fixed now (d3505032). It had to do with incorrect replacement of the Western Land character models.
