### ISSUE TITLE
Decorative Star space missing from website?

### ISSUE THREAD

**Issue by teconmoon** [PartyPlanner64/PartyPlanner64#38]
Was using the editor earlier in the day and had access to the decorative star space which I was using for a project, but not it's not a selectable space type? Did this addition get chopped? Thanks for reading!

![capture](https://cloud.githubusercontent.com/assets/17582898/20727424/47fd2276-b62e-11e6-8564-f619efe82e9c.PNG)
![capture2](https://cloud.githubusercontent.com/assets/17582898/20727425/480e4042-b62e-11e6-8175-68a7a9fd2f4f.PNG)
![capture3](https://cloud.githubusercontent.com/assets/17582898/20727426/48199816-b62e-11e6-9ee8-9fdf2140379b.PNG)

**Comment by PartyPlanner64** [comment]
Additional kinds of spaces will appear only when the Advanced features is checked on the settings page. The star spaces are one of those, because typically they aren't useful and usually the star marking is what someone wants.
