### ISSUE TITLE
MP3: Game crashes right before map is started

### ISSUE THREAD

**Issue by briancamarda** [PartyPlanner64/PartyPlanner64#39]
This is specifically happening on an Everdrive and I haven't been able to reproduce it on emulator.
I have been able to play other boards that others have created for MP3, but I'm not sure what is keeping this map from starting. 
I had fixed all of the overwrite rom errors and issues before writing and saving the rom. The only thing that I can think of is if there is a limit to the filesize of the images. I was using this more as an experiment to play with the PP64 tool and learn the ins and outs so I didn't optimize any of the images to match resolutions or anything, but it did seem that the tool resized everything for me.

Update: Resized all the images, and it still just gets stuck on a black screen. It happens right after you go to hit the dice block to see who goes first.

Update 2: I was able to get the game to load fully on the everdrive by changing these star sections. We had finished with our board layout before seeing the 8 star minimum requirement for Chilly Waters and this was our "fix" so we didn't have to put more star spaces through out the map. Removing these areas so it is only a one path, one star intersection fixed it. Not sure if you could provide information on why what I had was illegal for actual hardware.
![untitled](https://cloud.githubusercontent.com/assets/8310827/21295226/7286bc38-c51e-11e6-9490-02d08578c0ea.jpg)

![image](https://cloud.githubusercontent.com/assets/8310827/21295247/f34482d8-c51e-11e6-8cf4-9433ef838ce9.png)

[Koopa Troopa Beach.txt](https://github.com/PartyPlanner64/PartyPlanner64/files/659126/Koopa.Troopa.Beach.txt)

**Comment by PartyPlanner64** [comment]
To clarify, the first image is the fix? Did you bypass the overwrite errors in order to get a ROM with less than 8 stars? Because that would definitely not be bad, need to have 8.

**Comment by PartyPlanner64** [comment]
Closing this issue, not enough information to identify a specific problem.
