### ISSUE TITLE
Takes long to overwrite ROM

### ISSUE THREAD

**Issue by MusicalMatt** [PartyPlanner64/PartyPlanner64#40]
I have been sitting at my PC for about an hour now, and the loading screen with the moving pencil is still there after selecting a board to overwrite and beginning the loading process.

Is this a bug, or something it should usually do?

**Comment by MusicalMatt** [comment]
It has been loading for about 16 hours, and still nothing has happened.

**Comment by PartyPlanner64** [comment]
It should only take a couple seconds at most. If it hangs then there was some error in the browser.

Which browser are you using? Can you press F12 to open the dev tools and see if there is an error in the Console?

**Comment by MusicalMatt** [comment]
I have tried overwriting my map with both Firefox and Chrome, but nothing has worked. Although, the only thing in the console was a line that read:
"Uncaught Cannot write CHAINSPLIT, missing helper1[1]."

**Comment by PartyPlanner64** [comment]
That's a problem for sure. The editor relies on reading a mostly stock ROM so that it can cache certain game routines and later use them when overwriting. Is there a chance the ROM you are loading is corrupted or has already been edited somehow? Maybe try to get a different copy.

**Comment by MusicalMatt** [comment]
I downloaded another copy of the game, but no, it still loads for a long time.

Does it have to do with the aspects of the custom map made?

**Comment by PartyPlanner64** [comment]
With the error mentioned, I wouldn't think so. (`CHAINSPLIT` just means you have a branching path which is pretty much always the case.) But other than just trying different browsers / ROMs, maybe you could upload the board that is causing trouble ("Export board") and I could see if it happens for me.

**Comment by MusicalMatt** [comment]
[Baby Park.zip](https://github.com/PartyPlanner64/PartyPlanner64/files/692416/Baby.Park.zip)

Here it is. It's a super simple test map, so it's not high quality or creative at all.

**Comment by PartyPlanner64** [comment]
This board should be failing the error checking, did you check "Skip Board Validation" setting by accident? The main issue is that there needs to be 7 spaces marked as star spaces. A warning-level error is that the last bowser space around the loop has an odd path split; it points back two spaces as well as forward (not easy to see unless you drag it around).

**Comment by MusicalMatt** [comment]
Is there any way I can only have a possible star space in one spot without it having a warning?

**Comment by MusicalMatt** [comment]
Also, I was able to get it to work! Thanks a lot, and I appreciate spending your time looking into this.

**Comment by PartyPlanner64** [comment]
At the moment, it is hard-coded to the same amount the original board had. It seems very likely the amount could be lowered, and maybe increased someday. The existing game code needs to be studied more to see what exactly must be changed to allow this.
