### ISSUE TITLE
My hud glitches out all the time

### ISSUE THREAD

**Issue by HelpWantedOk** [PartyPlanner64/PartyPlanner64#42]
A lot of the screen such as the Coins character icon and such glitch in and out while I play a map. No idea how to fix this
![image](https://cloud.githubusercontent.com/assets/25357143/22315483/8e3e5a2c-e32c-11e6-8c2e-4c1ab4f30546.png) 
![image](https://cloud.githubusercontent.com/assets/25357143/22315488/992917ec-e32c-11e6-88c3-7c4dd371d97d.png)

**Comment by PartyPlanner64** [comment]
This is most likely an emulator issue, if I remember correctly "Mupen" is the emulator where this can happen. I would say try some different emulators or video plugins until you find one that works for you.
