### ISSUE TITLE
MP3: Characters

### ISSUE THREAD

**Issue by jakjake32** [PartyPlanner64/PartyPlanner64#46]
Dont know what happened, but daisy and waluigi are unusable now. the css opens and they are '?'

**Comment by PartyPlanner64** [comment]
Someone wrote up some information about this here. It is a general issue with running MP3 from an emulator.

https://tcrf.net/Mario_Party_3#Locked_Waluigi_and_Daisy

**Comment by PartyPlanner64** [comment]
This should be fixed now due to a patch done some months ago.
