### ISSUE TITLE
opening index does nothing

### ISSUE THREAD

**Issue by steampunko** [PartyPlanner64/PartyPlanner64#47]
It results in a white webpage with nothing on it
![yeah](https://cloud.githubusercontent.com/assets/16859299/25779141/f0c9d8e0-32c5-11e7-82aa-308274fca264.PNG)

and yes, I did extract it from the zip

**Comment by PartyPlanner64** [comment]
What does the F12 console say? It could be some permissions issues when running from `file:///`.

**Comment by steampunko** [comment]
It seems there are missing files?
![kkk](https://cloud.githubusercontent.com/assets/16859299/25784839/bf4c8b38-3328-11e7-8e82-180299ebda86.PNG)

**Comment by PartyPlanner64** [comment]
You should open the `index.html` that is present in the `dist` folder rather than the one in the root folder. The one in the root folder is the pre-processed version, while the contents in `dist` have been "built" already.
