### ISSUE TITLE
Enhancement - More variety of happening spaces events

### ISSUE THREAD

**Issue by Optimoro** [PartyPlanner64/PartyPlanner64#48]
Firstly, I would like to voice my thanks to all who have been working in this project. However, I believe there is a crippling lack of a variety in what happening spaces can do. I understand that it is a complicated issue, but happening spaces are part of what made Mario Party and its sequels' boards special and distinctive from one another. As such, it would be good to be able to use them for more than for the happening space star and game variety, but at least to warp players around?

**Comment by StalfosKing** [comment]
If it is possible to make smaller effects, such as teleporting players as you mentioned, or other simple happenings, this is the perfect solution to the problem. Also, if it's possible to use happenings from normal boards this would work excellently.

**Comment by PartyPlanner64** [comment]
The [custom events](https://github.com/PartyPlanner64/PartyPlanner64/wiki/Custom-Events) functionality is the fix for this enhancement request. People are able to create and add custom events to happening spaces, and many examples are out using this. Closing this issue :+1:
