### ISSUE TITLE
Crashing when passing bank spaces with high space-count (MP3)

### ISSUE THREAD

**Issue by StalfosKing** [PartyPlanner64/PartyPlanner64#53]
The board I've been working on for the current contest is quite large and sprawling... It seems that as a result of the high space-count, the game crashes every time I pass a bank space. I tried many, many tweaks to see the cause, and I do strongly believe it is the amount of total spaces. There seemed to be an element of randomness when I was tweaking the board and/or space count to try to stop the crashes, however; at times one bank worked and the other didn't, at others neither worked, and finally I was able to prevent the crashes altogether by greatly reducing space count. This "randomness" suggests other unseen variables. I will attach the board file after the contest is over... It is not submitted yet.

**Comment by StalfosKing** [comment]
I should be more specific; it seems not to be a crash, but perhaps a softlock, but I am not sure of the difference entirely. I think this because the music continues to play. Also, the crash occurs both on real hardware and in-emulator.

**Comment by PartyPlanner64** [comment]
I'm speculating that there is instability when the space count exceeds 128 spaces. For now I have implemented a warning that will let you know when you've exceeded that amount.

Specifically, the board in question had the banks on spaces with high indices (> 128), and this caused issues when the game tried to show the bank when passing. You can see the numbers assigned to each space by enabling Debug features in the settings.

**Comment by StalfosKing** [comment]
I will keep these things in mind when I port the board back to MP3... Thanks for the information!
