### ISSUE TITLE
Flickering Black Boxes on Mario Party 2 Backgrounds when Animated

### ISSUE THREAD

**Issue by StalfosKing** [PartyPlanner64/PartyPlanner64#55]
When I use more than one frame on my board, there are black flickering boxes that sometimes appear depending on where the player is on the board, particularly in the top-left in this case, but not sure if there are more areas. I'll send you the board through email.

**Comment by PartyPlanner64** [comment]
The game engine has some limitations as to how much imagery it can swap out for animations. When that limit is exceeded it starts to flicker. My rough estimate would be that you can't have more than half of the screen (at runtime) being animated. (The board image is divided into 64x48 tiles, so specifically you should try to avoid having more than half of those changing on screen in a single frame.)

The example board sent looks like it has quite a bit of animated changes in the upper left corner. If it can be toned down a bit, the issue should subside.

**Comment by PartyPlanner64** [comment]
Closing since there is no apparent way to fix this issue.

**Comment by SpeedyYoshi64** [comment]
Don't you have a wontfix tag?
