### ISSUE TITLE
Mario Party 3 Custom Boards dont work on Everdrive! (Crash)

### ISSUE THREAD

**Issue by JMGO-N64** [PartyPlanner64/PartyPlanner64#56]
Mario Party 1 and 2 custom boards works great on Everdrive, but MP3 custom boards crash after the presentation of the board, why?, Is the Partyplanner 64 focused on running the games on emulators and not on real hardware?, I whould be so sad If this is true!, I've already made 20 MP1 Custom boards, 12 MP2 Custom boards Whit work great, but only 9 MP3 custom boards with all have crashed in the presentation of the board when i try to run it in my Everdrive 64 Plus!, Please solve this ploblem!

**Comment by JMGO-N64** [comment]
I am waiting for Answers!!!

**Comment by SpeedyYoshi64** [comment]
???
