### ISSUE TITLE
Enhancement: Mini Game Stadium and Mini Game Coaster Music support on Mario Party 2.

### ISSUE THREAD

**Issue by JMGO-N64** [PartyPlanner64/PartyPlanner64#60]
When making a Custom board for Mario Party 2, i wanted to put the music of the Mini Game Coaster to play in it, but the music is nowhere to be found in the music list, as well the Mini Game Stadium theme in both Mario Party 2 & 1!
Why we cannot ad these musics to the Custom boards?, Please ad this musics in the list of Partyplanner 64, i would love to have a Custom board with the World 6 music from Mini Game Coaster!

**Comment by PartyPlanner64** [comment]
It is very possible that I have mislabeled the audio that is listed in the program. When I made the list I listened to the different songs and didn't necessarily figure out what their exact names were. So if you do find that it is mislabeled, let me know.

**Comment by PartyPlanner64** [comment]
I believe these are now available, more songs have been correctly identified.
