### ISSUE TITLE
Add "space boundary guide" to discourage placing spaces far to edge

### ISSUE THREAD

**Issue by PartyPlanner64** [PartyPlanner64/PartyPlanner64#66]
The editor could (by default) have a region boxed off that suggests where spaces should go. SuperZambezi improvised something like this on his stream.

![Example bounds](https://i.imgur.com/M2QgNCX.png)

I'd probably just make it a dotted line around the area. I'd make a setting to disable it.

**Comment by SpeedyYoshi64** [comment]
That's good to know. ^^

**Comment by PartyPlanner64** [comment]
Closing this, as the new Telescope feature includes the space boundary and helps diagnose when spaces are too close to the edge.
