### ISSUE TITLE
About patches on the ROM.

### ISSUE THREAD

**Issue by Spongyoshi** [PartyPlanner64/PartyPlanner64#67]
I wanna know how does the patching of a ROM works! What kinds of codes does it accept? I haven't seen it being documented it so sorry if I missed it because I searched :(
It would be awesome if you could add a code to unlock everything for example!! And it would make it more practical for me to use codes on Mario Party in general!

**Comment by PartyPlanner64** [comment]
I've added a page to the wiki mentioning the feature. You can paste Gameshark codes into the Cheats box and it will embed them into the ROM.

https://github.com/PartyPlanner64/PartyPlanner64/wiki/Gameshark-Cheats
