### ISSUE TITLE
Patches Don't Seem to Work

### ISSUE THREAD

**Issue by XModxGodX** [PartyPlanner64/PartyPlanner64#68]
I can't seem to get any gameshark cheats to work for any Mario Party using the "Patches" option it just ends up not even getting to the title screen no matter what game, cheat, or emulator I tried.

**Comment by PartyPlanner64** [comment]
I tried the following "skip n64 logo and intro" code for Mario Party 3 and it worked for me. The cheats [here](https://sites.google.com/site/gamemasterplcscheatcodes/nintendo-64/mario-party-3) should be reliable.

```
D10CE202 0058
810CE202 0079
```

**Comment by XModxGodX** [comment]
I just tried that exact code it says "patches applied" and I generated a ROM not even altering any of the boards or anything and it gives me a black screen with no error messages or anything. For the record here are my settings: 
![capture](https://user-images.githubusercontent.com/22751086/45601366-acdfaf00-b9c0-11e8-95b5-47dc32cc4a61.PNG)

**Comment by PartyPlanner64** [comment]
I hadn't seen issues with Nemu, but when I tried Mupen64plus now, I do get a black screen. It will need further investigating.

**Comment by PartyPlanner64** [comment]
I pushed out a fix for this just now, let me know if it doesn't resolve it. Thanks for reporting the issue!

**Comment by XModxGodX** [comment]
That seems to have fixed it thank you very much!
