### ISSUE TITLE
Cant Play any MP2 Map (Project 64 2.3 = Freeze, Nemu64 = Graphical bugs)

### ISSUE THREAD

**Issue by AndreasZiagl** [PartyPlanner64/PartyPlanner64#75]
I get the correct US Rom (correct checksum).

In Project64 2.3 it stops if the first player start. (for Example "MARIO START") Than it freeze.
In Nemu64 it runs but there is another problem with the camera. I see the board (only the image) but nothing else. You only hear the character moving.

What can I do? Nothing works :(

I have tested it with maps that must be work from Mario Party Legacy.

Is there an setting für Nemu64 für Mario Party 2? (in Nemu64 also the original MP2 have this bugs) Or any option for Project 64 2.3?

I have changed the RAM to 8MB and Counter Factor to 1.

**Comment by PartyPlanner64** [comment]
I double checked a MP2 board on my end, with Project64 2.4. I have a [nightly build](https://www.pj64-emu.com/nightly-builds) I use.

Are there any specific boards that are causing trouble?

I'm thinking this sounds like a graphics plugin issue. With nemu I use "Mudlord's Rice Video Build 6.1.4" or "Jabo's Direct3D8 1.6.1" I think. For Project64 I just use the default.

**Comment by AndreasZiagl** [comment]
Ok thanks with Project64 2.4 it works. :)
