### ISSUE TITLE
error: invalid value in setUint16

### ISSUE THREAD

**Issue by rileyvl** [PartyPlanner64/PartyPlanner64#76]
Can someone help me with this error. It happens when overwriting any board for any game. i tried it with multiple board and on multiple pc’s it just won’t work. I pressed f12 to look for errors and it says: invalid value in setUint16. It happens every time i try

**Comment by PartyPlanner64** [comment]
Are there any additional details? I don't see this happening on my end.

- Any specific boards that you've tried?
- Which browser are you using?
- Is there any call stack included with the error message in the console?

**Comment by rileyvl** [comment]
No call stack. No specific board (none work). And I use mario party 3 bowser spaces no bowser on the board

**Comment by PartyPlanner64** [comment]
Fixed the issue (eb65b681), it occurred if the background music was not set for a 2/3 board prior to trying to overwrite. The website has been updated with the fix, windows builds will be fixed next time they are created. Thanks!

**Comment by SpeedyYoshi64** [comment]
Thanks for fixing the issue!
