### ISSUE TITLE
Support custom audio

### ISSUE THREAD

**Issue by PartyPlanner64** [PartyPlanner64/PartyPlanner64#8]
Right now, PartyPlanner64 just treats the ROM audio section as one large binary chunk, and the only concern it has is that pointers to it are updated when packing the ROM.

PartyPlanner64 should initially be able to understand the audio section a bit more. It definitely has some sort of structure that could be parsed more finely.

Long term goal is to support custom audio tracks for boards.

**Comment by P3rf3ctXZer0** [comment]
I second this so I can add Kirby Party

**Comment by PartyPlanner64** [comment]
Would be neat, pretty complex though.

SubDrag posted some interesting information:
http://www.mariopartylegacy.com/forum/index.php?topic=16236.0

**Comment by WillieDangerously** [comment]
I second this. I'm already amazed at what you've made so far and can't wait to see this project flourish even more!

**Comment by SpeedyYoshi64** [comment]
When are you going to add it in?

**Comment by P3rf3ctXZer0** [comment]
I like sub drags tutorial but I am not a coder and the steps look overwhelming. I would rather just drag and drop a midi in party planner or mp3 and have it code itself.

**Comment by PartyPlanner64** [comment]
Functionality to support [custom midis](https://github.com/PartyPlanner64/PartyPlanner64/wiki/Creating-a-Board#background-music) for a board was added a few months ago, so I am closing this issue. It is far from perfect (ex: #118) but we can file individual issues for specific things going forward.
