### ISSUE TITLE
Bug when exiting audio player when audio is playing

### ISSUE THREAD

**Issue by lade1rex** [PartyPlanner64/PartyPlanner64#80]
I know the audio player is experimental atm, I just thought I should mention this bug just to be safe. When using the audio player, if you return to the editor without stopping the music, then go back to the music player, you are unable to stop the music that is currently playing, and can have multiple songs playing at the same time.

**Comment by PartyPlanner64** [comment]
Fixed in ce00a98 by having the music stop when leaving the Audio page. Thanks!
