### ISSUE TITLE
Ability to interact with multiple spaces at once

### ISSUE THREAD

**Issue by PartyPlanner64** [PartyPlanner64/PartyPlanner64#9]
The renderer should be able to support selecting multiple spaces at once.
- Should be able to move multiple spaces at once.
- Ideally be able to change the type/subtype of multiple spaces at once.
- Holding ctrl and clicking should also work.

**Comment by StalfosKing** [comment]
This would be incredibly useful and speed up workflow massively in my opinion.

**Comment by PartyPlanner64** [comment]
Multi-select has been added and pushed to production (e79ee5a7, 72f3b6cf)

- Ctrl clicking a space with the move tool will "add" it to the current selections.
- Spaces can also be dragged over to select a bunch of them, also with the move tool.
- When multiple spaces are selected, a subset of the "Space properties" options are available. You can change the type of all selected spaces simultaneously.
- The delete key and arrow keys will affect all selected spaces.
