### ISSUE TITLE
(Wiki) Updating MP2 Filesystem Listing

### ISSUE THREAD

**Issue by Gregery94** [PartyPlanner64/PartyPlanner64#90]
Is there an updated list for MP2 that can be pushed? https://github.com/PartyPlanner64/PartyPlanner64/wiki/Main-Filesystem-Listing

I had begun filling in the blanks in excel but do not want to do something that had been done already.

**Comment by PartyPlanner64** [comment]
Nope, I don't have any notes on those. If you'd like to see it updated, feel free to post some here and I'll add them to the wiki!

**Comment by PartyPlanner64** [comment]
Closing this github issue, as updates have been coming in for this page since opening the wiki for updates by other users.
