### ISSUE TITLE
Website doesn't allow to overwrite boards of Mario Party 1

### ISSUE THREAD

**Issue by IggyKoopaSaurus** [PartyPlanner64/PartyPlanner64#91]
I have a problem with the PartyPlanner64 website. Because when I try to overwrite boards of MP1, a message appears saying "Error overwriting the board". But when I try to overwrite boards of MP1 in the   PartyPlanner64 Setup.exe, that doesn't happen.

**Comment by IggyKoopaSaurus** [comment]
![errir](https://user-images.githubusercontent.com/64039054/79791570-88c21d80-831b-11ea-876a-c3c9fcc30338.PNG)

**Comment by PartyPlanner64** [comment]
Fixed this in the latest publish. Also made it so that errors like this will show the actual error text on screen, instead of only in the browser console.
