### ISSUE TITLE
Game doesnt load minigames! (MP1)

### ISSUE THREAD

**Issue by SomethingRando123** [PartyPlanner64/PartyPlanner64#95]

**Comment by SomethingRando123** [comment]
Ok, i went back and tried again, it ran at correct speed and no flickering(even though i was not using glide 64) but the problem persists.

**Comment by SomethingRando123** [comment]
Never mind, issue solved itself, i had to change memory size from 8mb to default.

**Comment by SomethingRando123** [comment]
Now minigames wont work, every setting is correct.

**Comment by PartyPlanner64** [comment]
Could you clarify:

- What board were you writing?
- What original board was being replaced?

**Comment by SomethingRando123** [comment]
By writing do you mean which board was overwriten on?  That would be Mario;s rainbow ride. The board I was writing was a custom one by me.

**Comment by SomethingRando123** [comment]
I was using Project 64 v1.6. Some weird stuff would happen such as I had to use 4mb or defaualt to make it so I would not get a black screen after choosing the warp pipe.

**Comment by PartyPlanner64** [comment]
Mario's Rainbow Castle is not supported for overwrite currently. Only the first four MP1 boards are supported for overwrite currently.

You'll want to go into Settings and disable "Skip Overwrite Validation" which must have been enabled at one point.

**Comment by SomethingRando123** [comment]
Ah, Thanks for the tip.

**Comment by SomethingRando123** [comment]
Well the minigames still don't load, just a black screen.

**Comment by SomethingRando123** [comment]
Wait, Project 64 v1.6 does not work but v2.3.2 works! So yeah, jsut use that version.
